FROM ubuntu:18.04

# Install Base dependencies and utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl gnupg vim
RUN echo 'alias ll='"'"'ls $LS_OPTIONS -al'"'"'' >> ~/.bashrc 

# Install Python 3.7 
RUN apt-get update &&  apt-get install -y \
    build-essential zlib1g-dev libncurses5-dev libgdbm-dev \
    libnss3-dev libssl-dev libreadline-dev libffi-dev wget
WORKDIR /tmp
RUN wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz \
    && tar -xf Python-3.7.2.tar.xz 
WORKDIR /tmp/Python-3.7.2
RUN ./configure --enable-optimizations 
RUN make -j 1 
# RUN make altinstall
RUN make install
RUN /usr/local/bin/python3.7 -m pip install --upgrade pip

# make some useful symlinks that are expected to exist
RUN cd /usr/local/bin \
	&& ln -s idle3 idle \
	&& ln -s pydoc3 pydoc \
	&& ln -s python3 python \
	&& ln -s python3-config python-config

# Install SQL DW Driver
# Instructions at https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17

# install pyodbc
# Instructions from https://github.com/mkleehammer/pyodbc/wiki/Install
RUN apt-get install -y unixodbc-dev 

# Copy local project
COPY requirements.txt /app/
WORKDIR /app
RUN /usr/local/bin/python3 -m pip install -r requirements.txt

# RUN pip install -r requirements.txt
COPY merge_temp.py ./script/

# CMD ["/usr/local/bin/python3", "/app/script/merge_temp.py"]
ENTRYPOINT [ "/bin/bash" ]