repos:
    - repo: 'https://github.com/pycqa/isort'
      rev: 5.13.2
      hooks:
        - id: isort
    - repo: 'https://github.com/codespell-project/codespell'
      rev: v2.2.6
      hooks:
        - id: codespell
          args:
            - '--skip="./.*,*.csv,*.json,*.pyc,./docs/_build/*,./htmlcov/*"'
            - '--quiet-level=2'
          exclude_types:
            - csv
            - json
    - repo: 'https://github.com/psf/black'
      rev: 24.3.0
      hooks:
        - id: black
          args:
            - '--safe'
            - '--quiet'
    - repo: 'https://github.com/pycqa/flake8'
      rev: 7.0.0
      hooks:
        - id: flake8
          additional_dependencies:
            - flake8-docstrings==1.6.0
            - pydocstyle==6.3.0
          files: ^main.py|(script)\/.+\.py$
    - repo: 'https://github.com/PyCQA/bandit'
      rev: 1.7.8
      hooks:
        - id: bandit
          args:
            - '--quiet'
            - '--format=custom'
            - '--configfile=pyproject.toml'
          additional_dependencies: [".[toml]"]

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
        - id: pydocstyle
          additional_dependencies: [ toml ]
    - repo: 'https://github.com/pre-commit/pre-commit-hooks'
      rev: v4.5.0
      hooks:
        - id: check-docstring-first
        - id: check-shebang-scripts-are-executable
        - id: check-toml
        - id: check-yaml
          args: [--unsafe]
        - id: end-of-file-fixer
        - id: fix-byte-order-marker
        - id: mixed-line-ending
        - id: trailing-whitespace
    - repo: local
      hooks:
        - id: shellcheck
          name: shellcheck
          entry: script/pre_commit_shellcheck.sh
          language: script
          exclude_types: [json, sql, toml, yaml]
          files: ^(script|iac)/.+sh$
        - id: pylint
          name: pylint
          entry: script/run_in_env.sh pylint -j 0
          language: script
          types: [python]
          files: ^functions/.+\.py$
