"""Module to manage billing."""

DEFAULT_CHUNK_SIZE = 500000

BILLING_DTYPES = {
    "InvoiceSectionName": "object",
    "AccountName": "object",
    "AccountOwnerId": "object",
    "SubscriptionId": "object",
    "SubscriptionName": "object",
    "ResourceGroup": "object",
    "ResourceLocation": "object",
    "Date": "datetime64[ns]",
    "ProductName": "object",
    "MeterCategory": "object",
    "MeterSubCategory": "object",
    "MeterId": "object",
    "MeterName": "object",
    "MeterRegion": "object",
    "UnitOfMeasure": "object",
    "Quantity": "float64",
    "EffectivePrice": "float64",
    "CostInBillingCurrency": "float64",
    "CostCenter": "object",
    "ConsumedService": "object",
    "ResourceId": "object",
    "Tags": "object",
    "OfferId": "object",
    "AdditionalInfo": "object",
    "ServiceInfo1": "object",
    "ServiceInfo2": "object",
    "ResourceName": "object",
    "ReservationId": "object",
    "ReservationName": "object",
    "UnitPrice": "float64",
    "ProductOrderId": "object",
    "ProductOrderName": "object",
    "Term": "object",
    "PublisherType": "object",
    "PublisherName": "object",
    "ChargeType": "object",
    "Frequency": "object",
    "PricingModel": "object",
    "AvailabilityZone": "object",
    "BillingAccountId": "object",
    "BillingAccountName": "object",
    "BillingCurrencyCode": "object",
    "BillingPeriodStartDate": "datetime64[ns]",
    "BillingPeriodEndDate": "datetime64[ns]",
    "BillingProfileId": "object",
    "BillingProfileName": "object",
    "InvoiceSectionId": "object",
    "IsAzureCreditEligible": "object",
    "PartNumber": "object",
    "PayGPrice": "float64",
    "PlanName": "object",
    "ServiceFamily": "object",
    "CostAllocationRuleName": "object",
    "benefitId": "object",
    "benefitName": "object",
}

BILLING_COLUMN_NAMES = [col for col, dt in BILLING_DTYPES.items()]


BILLING_DTYPES_OLD = {
    "AccountId": "int64",
    "AccountName": "object",
    "AccountOwnerEmail": "object",
    "AdditionalInfo": "object",
    "ConsumedQuantity": "float64",
    "ConsumedService": "object",
    "ConsumedServiceId": "int64",
    "Cost": "float64",
    "CostCenter": "object",
    "Date": "object",
    "DepartmentId": "int64",
    "DepartmentName": "object",
    "InstanceId": "object",
    "MeterCategory": "object",
    "MeterId": "object",
    "MeterName": "object",
    "MeterRegion": "object",
    "MeterSubCategory": "object",
    "Product": "object",
    "ProductId": "int64",
    "ResourceGroup": "object",
    "ResourceLocation": "object",
    "ResourceLocationId": "int64",
    "ResourceRate": "float64",
    "ServiceAdministratorId": "object",
    "ServiceInfo1": "object",
    "ServiceInfo2": "object",
    "StoreServiceIdentifier": "object",
    "SubscriptionGuid": "object",
    "SubscriptionId": "int64",
    "SubscriptionName": "object",
    "Tags": "object",
    "UnitOfMeasure": "object",
    "PartNumber": "object",
    "ResourceGuid": "object",
    "OfferId": "object",
    "ChargesBilledSeparately": "int64",
    "Location": "object",
    "ServiceName": "object",
    "ServiceTier": "object",
}
