FROM python:3.7-slim-stretch

# Build slim version similar to python slim https://github.com/docker-library/python/blob/master/3.7/stretch/Dockerfile

# extra dependencies (over what python-slim-stretch already includes)
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
        gnupg \
        vim \
        apt-transport-https \
        ca-certificates \
        g++ \
        unixodbc-dev \
    && rm -rf /var/lib/apt/lists/*

# Install SQL DW Driver
# Instructions at https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17 && rm -rf /var/lib/apt/lists/*

# install pyodbc
# Instructions from https://github.com/mkleehammer/pyodbc/wiki/Install

RUN python -m pip install --upgrade pip && python -m pip install pyodbc

# Error;
# Opened issue https://github.com/MicrosoftDocs/windowsserverdocs/issues/3735

# Copy local project
# COPY requirements.txt /app/
# WORKDIR /app
# RUN /usr/local/bin/python3 -m pip install -r requirements.txt

# COPY merge_temp.py ./script/

ENTRYPOINT [ "/bin/bash" ]
